# Generated by Django 5.2.2 on 2025-06-08 06:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('YOGA', 'Yoga'), ('ZUMBA', 'Zumba'), ('HIIT', 'HIIT'), ('PILATES', 'Pilates')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('total_slots', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('available_slots', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('timezone_name', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('fitness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.fitnessmodel')),
            ],
        ),
        migrations.AddField(
            model_name='fitnessmodel',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='booking.instructormodel'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='FitnessClass',
        ),
        migrations.AddIndex(
            model_name='bookingmodel',
            index=models.Index(fields=['client_email'], name='booking_boo_client__c4b392_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmodel',
            index=models.Index(fields=['booked_at'], name='booking_boo_booked__3b3ba6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingmodel',
            unique_together={('fitness', 'client_email')},
        ),
        migrations.AddIndex(
            model_name='fitnessmodel',
            index=models.Index(fields=['start_time'], name='booking_fit_start_t_77872d_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessmodel',
            index=models.Index(fields=['name'], name='booking_fit_name_f287c3_idx'),
        ),
    ]
