# Generated by Django 5.2.2 on 2025-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_fitnessmodel_class_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessmodel',
            options={'ordering': ['datetime_ist']},
        ),
        migrations.RemoveIndex(
            model_name='fitnessmodel',
            name='booking_fit_start_t_77872d_idx',
        ),
        migrations.RenameField(
            model_name='fitnessmodel',
            old_name='start_time',
            new_name='datetime_ist',
        ),
        migrations.RemoveField(
            model_name='fitnessmodel',
            name='timezone_name',
        ),
        migrations.AddIndex(
            model_name='fitnessmodel',
            index=models.Index(fields=['datetime_ist'], name='booking_fit_datetim_914163_idx'),
        ),
    ]
