# Generated by Django 5.0.6 on 2025-06-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('HIIT', 'HIIT')], max_length=50)),
                ('datetime_ist', models.DateTimeField(help_text='Datetime stored in IST')),
                ('instructor', models.CharField(max_length=100)),
                ('total_slots', models.PositiveIntegerField(default=10)),
                ('available_slots', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['datetime_ist'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.fitnessclass')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
