# Generated by Django 5.2.2 on 2025-06-08 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_fitnessmodel_instructormodel_bookingmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessmodel',
            name='class_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessmodel',
            name='days_of_week',
            field=models.CharField(default='', max_length=100),
        ),
    ]
